//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//

#include "stdafx.h"
#include "Bank.h"

bool Bank::wyplata(double ile, int nrKonta) {
	return false;
}

double Bank::wplata(double ile, int nrKonta) {
	return 0.0;
}

double Bank::stanKonta(int nrKonta) {
	return 0.0;
}

