//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.h
//  @ Date : 18.12.2016
//  @ Author : 
//
//


#if !defined(_BANK_H)
#define _BANK_H

#include "Konto.h"

class Bank {
public:
	bool wyplata(double ile, int nrKonta);
	double wplata(double ile, int nrKonta);
	double stanKonta(int nrKonta);
private:
	Konto *konta;
};

#endif  //_BANK_H
