//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bank.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//


#include "Bank.h"

bool Bank::wyplata(double ile, int nrKonta) {

}

double Bank::wplata(double ile, int nrKonta) {

}

double Bank::stanKonta(int nrKonta) {

}

