//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bankomat.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//


#include "Bankomat.h"

void Bankomat::wyplata(double ile, int nrKonta) {

}

void Bankomat::wp³ata(double ile, int nrKonta) {

}

void Bankomat::stanKonta(int nrKonta) {

}

void Bankomat::nowaSesja() {

}

void Bankomat::autoryzacjaPIN() {

}

void Bankomat::koniecSesji() {

}

