//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bankomat.h
//  @ Date : 18.12.2016
//  @ Author : 
//
//


#if !defined(_BANKOMAT_H)
#define _BANKOMAT_H

#include "Bank.h"
#include "stdafx.h"

class Bankomat {
public:
	int sesjaid;
	int nrKonta;
	int gotowka;
	void wyplata();
	void wplata();
	void stanKonta();
	void nowaSesja();
	void autoryzacjaPIN();
	void koniecSesji();
	Bank *bank;
};

#endif  //_BANKOMAT_H
