//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//

#include "stdafx.h"
#include "Konto.h"

using namespace std;

double Konto::wplata(double ile) {

	return 0.0;
}

bool Konto::wyplata(double ile) {
	return false;
}

double Konto::wyswietl_stan() {
	return 0.0;
}

