//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//


#include "Konto.h"

double Konto::wplata(double ile) {

}

bool Konto::wyplata(double ile) {

}

double Konto::wyswietl_stan() {

}

