//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Konto.cpp
//  @ Date : 18.12.2016
//  @ Author : 
//
//

#include "stdafx.h"
#include "Konto.h"

using namespace std;

double Konto::wplata(double ile) {

	stan += ile;
	return stan;
}

bool Konto::wyplata(double ile) {
	if (stan >= ile) {
		stan -= ile;
		return true;
	}
	else return false;
}

double Konto::wyswietl_stan() {
	return stan;
}

Konto::Konto(int _nrKonta, double _stan):  nrKonta(_nrKonta), stan(_stan)
{}
