//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Autor.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_AUTOR_H)
#define _AUTOR_H

#include <string>

using namespace std;

class Autor {
public:
	std::string imie;
	string nazwisko;
	Autor(string imie, string nazwisko);
};

#endif  //_AUTOR_H
