//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteka.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_BIBLIOTEKA_H)
#define _BIBLIOTEKA_H

#include "ElementKatalogowy.h"
#include "Klient.h"
#include "Personel.h"
#include <vector>


class Biblioteka {
public:
	bool rezerwacja(ElementKatalogowy element, Klient klient);
	void wypozyczenie(ElementKatalogowy element, Klient klient, Personel personel);
	void zwrot(ElementKatalogowy element, Klient klient, Personel personel);
	void zakup(ElementKatalogowy element, Personel personel);
	void likwidacja(ElementKatalogowy element, Personel personel);
	vector<ElementKatalogowy> katalog;
private:
	vector<ElementKatalogowy> elemetyZarezerwowane;
	vector<ElementKatalogowy> elementyWypozyczone;
	vector<Klient> wypozyczenia;
	bool czyMoznaRezerowac(ElementKatalogowy element);
	bool czyMoznaWypozyczyc(ElementKatalogowy element, Klient klient);
};

#endif  //_BIBLIOTEKA_H
