//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Czasopismo.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_CZASOPISMO_H)
#define _CZASOPISMO_H

#include "ElementKatalogowy.h"

class Czasopismo : public ElementKatalogowy {
};

#endif  //_CZASOPISMO_H
