//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElementKatalogowy.cpp
//  @ Date : 11.12.2016
//  @ Author : 
//
//

#include "stdafx.h"
#include "ElementKatalogowy.h"
#include <string>
using namespace std;

string ElementKatalogowy::opis() {

}

string ElementKatalogowy::szczegolowyOpis() {

}

