//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElementKatalogowy.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_ELEMENTKATALOGOWY_H)
#define _ELEMENTKATALOGOWY_H


class ElementKatalogowy {
public:
	int nrKat;
	string opis();
	string szczegolowyOpis();
};

#endif  //_ELEMENTKATALOGOWY_H
