//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Klient.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_KLIENT_H)
#define _KLIENT_H

#include "Osoba.h"

class Klient : public Osoba {
};

#endif  //_KLIENT_H
