//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ksiazka.cpp
//  @ Date : 11.12.2016
//  @ Author : 
//
//

#include "stdafx.h"
#include "Ksiazka.h"

string Ksiazka::opis() {

}

string Ksiazka::szczegolowypis() {

}

