//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Osoba.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_OSOBA_H)
#define _OSOBA_H
#include <string>

using namespace std;

class Osoba {
public:
	string Imie;
	string Nazwisko;
};

#endif  //_OSOBA_H
