//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Personel.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_PERSONEL_H)
#define _PERSONEL_H

#include "Osoba.h"

class Personel : public Osoba {
};

#endif  //_PERSONEL_H
