//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PlytaDVD.h
//  @ Date : 11.12.2016
//  @ Author : 
//
//


#if !defined(_PLYTADVD_H)
#define _PLYTADVD_H

#include "ElementKatalogowy.h"

class PlytaDVD : public ElementKatalogowy {
};

#endif  //_PLYTADVD_H
